GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/63a400801d40f72af07e9538
###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "get_all_notes.rest",
  "important": true
}
###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "important": true
}

###
DELETE  http://localhost:3001/api/notes/63a80dd650ececcb9ad723a6

###
PUT http://localhost:3001/api/notes/63a861fcd6e9ac4f176f1614
Content-Type: application/json

{
  "content": "get_all_notes.rest",
  "important": false
}