GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/67e9538
###
DELETE http://localhost:3001/api/notes/4
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Postman is a good tool for testing a REST-api",
    "important": true
}
###

PUT http://localhost:3001/api/notes/63a400801d40f72af07e9538
Content-Type: application/json

{
    "content": "HTML is Easy",
    "important": false
}